import type { ReactionDefinition } from '../types';

/**
 * 반응 골격 22개. 화학식·계수·원소 보존은 밸런스 조정 대상이 아니다.
 * energy/time 은 추상 비용이며 economy config 가 덮어쓸 수 있다.
 * outputs 는 배치(batchMultiplier × 최소비) 기준으로 실제 생기는 로트 스트림이다.
 */
const R = (r: ReactionDefinition) => r;

export const REACTIONS: Record<string, ReactionDefinition> = {
  R01: R({
    id: 'R01', name: '물 합성', equation: '2H2(g) + O2(g) → 2H2O(g)',
    reactants: [{ accepts: ['H2_g'], coef: 2 }, { accepts: ['O2_g'], coef: 1 }],
    products: [{ materialId: 'H2O_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'H2O_g', coef: 2 }], tags: ['reaction'] }],
    energy: 1, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '제어된 점화, 밀폐 회수', handling: '수증기를 응축(P01)해야 액체 물이 된다.',
    gasVolumeRatio: { label: 'H2 : O2 : H2O(g)', ratio: '2 : 1 : 2', note: '수증기가 기체인 동일 온도·압력 조건에서의 부피비' },
    scientificSources: ['OpenStax Chemistry 2e §9.3 (기체 화학량론)'],
    simplifications: ['점화 조건과 안전 장치는 추상화했다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R02: R({
    id: 'R02', name: '물 전기분해', equation: '2H2O(l) → 2H2(g) + O2(g)',
    reactants: [{ accepts: ['H2O_l'], coef: 2 }],
    products: [{ materialId: 'H2_g', coef: 2 }, { materialId: 'O2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'H2_g', coef: 2 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'O2_g', coef: 1 }], tags: ['gasCollected'] },
    ],
    energy: 4, time: 2, requiredEquipment: ['U05'], exothermic: false, heatRecoverable: false,
    conditions: '전해 모듈, 전극별 분리 수집', handling: '수소와 산소를 별도 기체로 수집한다.',
    gasVolumeRatio: { label: 'H2 : O2', ratio: '2 : 1', note: '생성 기체의 동일 조건 부피비' },
    scientificSources: ['일반화학 교과서: 물의 전기분해'],
    simplifications: ['전도성을 위한 전해질(예: 황산나트륨 소량)은 공정 보조물로 별도 기록하며 소모하지 않는다. 순수한 물에 전기만 통한다고 표현하지 않는다.'],
    modes: ['extended', 'industrial'], path: 'gas',
  }),
  R03: R({
    id: 'R03', name: '과산화수소 분해', equation: '2H2O2(aq) → 2H2O(l) + O2(g)',
    reactants: [{ accepts: ['H2O2_aq'], coef: 2 }],
    products: [{ materialId: 'H2O_l', coef: 2 }, { materialId: 'O2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'O2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'H2O_l', coef: 2 }], tags: ['solutionWater'], grade: 'recovered', solvent: 2 },
    ],
    energy: 0, time: 2, timeWithCatalyst: 1, catalystEquipment: 'U08', exothermic: true, heatRecoverable: false,
    conditions: '지정 분해 공정, MnO2 촉매 선택', handling: '산소를 수집하고 물은 용액 원장(회수수)으로 남긴다.',
    scientificSources: ['일반화학 교과서: 촉매에 의한 과산화수소 분해'],
    simplifications: ['용액 속 물은 회수수 등급이며 정제수 계약에는 쓸 수 없다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R04: R({
    id: 'R04', name: '메테인 완전 연소', equation: 'CH4(g) + 2O2(g) → CO2(g) + 2H2O(g)',
    reactants: [{ accepts: ['CH4_g'], coef: 1 }, { accepts: ['O2_g'], coef: 2 }],
    products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 2 }], tags: ['gasMixture'], mixture: true }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '산소가 충분한 완전 연소', handling: '기체 혼합물을 응축(P01)하면 물과 이산화탄소가 분리된다.',
    gasVolumeRatio: { label: 'CH4 : O2 : CO2 : H2O(g)', ratio: '1 : 2 : 1 : 2', note: '모두 기체인 동일 조건 부피비' },
    scientificSources: ['OpenStax Chemistry 2e §9.3'],
    simplifications: ['불완전 연소는 다루지 않는다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R05: R({
    id: 'R05', name: '마그네슘 연소', equation: '2Mg(s) + O2(g) → 2MgO(s)',
    reactants: [{ accepts: ['Mg_s'], coef: 2 }, { accepts: ['O2_g'], coef: 1 }],
    products: [{ materialId: 'MgO_s', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'MgO_s', coef: 2 }], tags: ['reaction'] }],
    energy: 1, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '점화, 산소 조건', handling: '산화마그네슘을 바로 회수한다.',
    scientificSources: ['일반화학 교과서: 금속의 연소'],
    simplifications: ['공기 중 질소와의 부반응은 생략했다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'metal',
  }),
  R06: R({
    id: 'R06', name: '탄산수소나트륨 열분해', equation: '2NaHCO3(s) → Na2CO3(s) + CO2(g) + H2O(g)',
    reactants: [{ accepts: ['NaHCO3_s'], coef: 2 }],
    products: [{ materialId: 'Na2CO3_s', coef: 1 }, { materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'Na2CO3_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 1 }], tags: ['gasMixture'], mixture: true },
    ],
    energy: 2, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '가열', handling: '고체와 기체 흐름을 장치 안에서 분리 수집. 기체는 응축(P01)으로 나눈다.',
    scientificSources: ['RSC Education: 탄산염의 가열'],
    simplifications: ['완전 분해로 가정한다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R07: R({
    id: 'R07', name: '탄산칼슘 침전', equation: 'Na2CO3(aq) + CaCl2(aq) → CaCO3(s) + 2NaCl(aq)',
    reactants: [{ accepts: ['Na2CO3_s'], coef: 1, dissolve: true }, { accepts: ['CaCl2_aq', 'CaCl2_s'], coef: 1, dissolve: true }],
    products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'NaCl_aq', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'NaCl_aq', coef: 2 }], tags: ['suspension'], mixture: true, solvent: 2 }],
    energy: 0, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '수용액, 침전', handling: '여과·세척(P02)으로 탄산칼슘을 회수하고 여액의 염화나트륨은 보존한다.',
    scientificSources: ['CU Boulder Lecture Demo S130: CaCl2 + Na2CO3 침전'],
    simplifications: ['고체 원료는 공정 용수로 용해하여 투입한다(용매 원장에 기록).'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R08: R({
    id: 'R08', name: '생석회 수화', equation: 'CaO(s) + H2O(l) → Ca(OH)2(s)',
    reactants: [{ accepts: ['CaO_s'], coef: 1 }, { accepts: ['H2O_l'], coef: 1 }],
    products: [{ materialId: 'CaOH2_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaOH2_s', coef: 1 }], tags: ['reaction'] }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '지정 수화 공정', handling: '수산화칼슘을 회수한다.',
    scientificSources: ['일반화학 교과서: 산화칼슘의 수화'],
    simplifications: [],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R09: R({
    id: 'R09', name: '석회수 탄산화', equation: 'Ca(OH)2(s) + CO2(g) → CaCO3(s) + H2O(l)',
    reactants: [{ accepts: ['CaOH2_s'], coef: 1, dissolve: true }, { accepts: ['CO2_g'], coef: 1 }],
    products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'H2O_l', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '수산화칼슘 수성 현탁계, CO2 과잉 금지', handling: '침전을 여과(P02)로 회수. CO2 과잉 시의 탄산수소염 경로는 이 공방에서 지원하지 않는다.',
    scientificSources: ['일반화학 교과서: 석회수의 백탁'],
    simplifications: ['과잉 CO2에 의한 Ca(HCO3)2 생성은 다루지 않는다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R10: R({
    id: 'R10', name: '중화', equation: 'HCl(aq) + NaOH(aq) → NaCl(aq) + H2O(l)',
    reactants: [{ accepts: ['HCl_aq'], coef: 1 }, { accepts: ['NaOH_aq'], coef: 1 }],
    products: [{ materialId: 'NaCl_aq', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'NaCl_aq', coef: 1 }], tags: ['reaction'], solvent: 3 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '중화', handling: '소금물이 생긴다. 결정화(P03)가 필요하다. 생성된 물은 용액에 합쳐진다.',
    scientificSources: ['일반화학 교과서: 산염기 중화'],
    simplifications: ['생성된 물 1칸은 용매 원장에 합산한다.'],
    modes: ['extended', 'industrial'], path: 'water',
  }),
  R11: R({
    id: 'R11', name: '탄산칼슘과 염산', equation: 'CaCO3(s) + 2HCl(aq) → CaCl2(aq) + CO2(g) + H2O(l)',
    reactants: [{ accepts: ['CaCO3_s'], coef: 1 }, { accepts: ['HCl_aq'], coef: 2 }],
    products: [{ materialId: 'CaCl2_aq', coef: 1 }, { materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CO2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'CaCl2_aq', coef: 1 }], tags: ['reaction'], solvent: 3 },
    ],
    energy: 0, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '산·탄산염', handling: '기체는 수집하고 용액은 별도 로트로 남긴다.',
    scientificSources: ['일반화학 교과서: 탄산염과 산의 반응'],
    simplifications: ['생성된 물은 용매 원장에 합산한다.'],
    modes: ['extended', 'industrial'], path: 'carbonate',
  }),
  R12: R({
    id: 'R12', name: '마그네슘과 염산', equation: 'Mg(s) + 2HCl(aq) → MgCl2(aq) + H2(g)',
    reactants: [{ accepts: ['Mg_s'], coef: 1 }, { accepts: ['HCl_aq'], coef: 2 }],
    products: [{ materialId: 'MgCl2_aq', coef: 1 }, { materialId: 'H2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'H2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'MgCl2_aq', coef: 1 }], tags: ['reaction'], solvent: 2 },
    ],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '산·금속', handling: '수소를 수집하고 용액은 별도 로트로 남긴다.',
    scientificSources: ['일반화학 교과서: 금속과 산의 반응'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R13: R({
    id: 'R13', name: '아연의 구리 치환', equation: 'Zn(s) + CuSO4(aq) → ZnSO4(aq) + Cu(s)',
    reactants: [{ accepts: ['Zn_s'], coef: 1 }, { accepts: ['CuSO4_aq'], coef: 1 }],
    products: [{ materialId: 'ZnSO4_aq', coef: 1 }, { materialId: 'Cu_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'ZnSO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '금속 치환', handling: '구리를 여과(P02)로 회수한다.',
    scientificSources: ['일반화학 교과서: 금속의 반응성 서열'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R14: R({
    id: 'R14', name: '산화구리 환원', equation: 'CuO(s) + H2(g) → Cu(s) + H2O(g)',
    reactants: [{ accepts: ['CuO_s'], coef: 1 }, { accepts: ['H2_g'], coef: 1 }],
    products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'Cu_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'H2O_g', coef: 1 }], tags: ['reaction'] },
    ],
    energy: 2, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '가열·환원', handling: '구리와 수증기를 별도 흐름으로 수집한다.',
    scientificSources: ['일반화학 교과서: 금속 산화물의 환원'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R15: R({
    id: 'R15', name: '탄산칼슘 열분해', equation: 'CaCO3(s) → CaO(s) + CO2(g)',
    reactants: [{ accepts: ['CaCO3_s'], coef: 1 }],
    products: [{ materialId: 'CaO_s', coef: 1 }, { materialId: 'CO2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CaO_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'CO2_g', coef: 1 }], tags: ['gasCollected'] },
    ],
    energy: 3, time: 2, exothermic: false, heatRecoverable: false,
    conditions: '고온 분해', handling: '탄산칼슘을 직접 납품하는 것과 선택 관계다.',
    scientificSources: ['RSC Education: 탄산염의 가열'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'carbonate',
  }),
  R16: R({
    id: 'R16', name: '수산화구리 침전', equation: 'CuSO4(aq) + 2NaOH(aq) → Cu(OH)2(s) + Na2SO4(aq)',
    reactants: [{ accepts: ['CuSO4_aq'], coef: 1 }, { accepts: ['NaOH_aq'], coef: 2 }],
    products: [{ materialId: 'CuOH2_s', coef: 1 }, { materialId: 'Na2SO4_aq', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CuOH2_s', coef: 1 }, { materialId: 'Na2SO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 3 }],
    energy: 0, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '침전', handling: '고체를 여과(P02)로 회수한다.',
    scientificSources: ['일반화학 교과서: 침전 반응'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R17: R({
    id: 'R17', name: '수산화구리 열분해', equation: 'Cu(OH)2(s) → CuO(s) + H2O(g)',
    reactants: [{ accepts: ['CuOH2_s'], coef: 1 }],
    products: [{ materialId: 'CuO_s', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CuO_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'H2O_g', coef: 1 }], tags: ['reaction'] },
    ],
    energy: 2, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '가열 분해', handling: '수증기는 응축(P01) 뒤에만 액체 물로 기록한다.',
    scientificSources: ['일반화학 교과서: 수산화물의 열분해'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R18: R({
    id: 'R18', name: '철의 구리 치환', equation: 'Fe(s) + CuSO4(aq) → FeSO4(aq) + Cu(s)',
    reactants: [{ accepts: ['Fe_s'], coef: 1 }, { accepts: ['CuSO4_aq'], coef: 1 }],
    products: [{ materialId: 'FeSO4_aq', coef: 1 }, { materialId: 'Cu_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'FeSO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '금속 치환', handling: '구리를 여과(P02)로 회수한다. 아연 경로와 원가를 비교하라.',
    scientificSources: ['일반화학 교과서: 금속의 반응성 서열'],
    simplifications: ['Fe(s) 원료와 Fe 촉매 모듈(U09)은 역할과 재고가 다르다.'],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R19: R({
    id: 'R19', name: '염화암모늄 합성', equation: 'NH3(g) + HCl(g) → NH4Cl(s)',
    reactants: [{ accepts: ['NH3_g'], coef: 1 }, { accepts: ['HCl_g'], coef: 1 }],
    products: [{ materialId: 'NH4Cl_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'NH4Cl_s', coef: 1 }], tags: ['reaction'] }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '지정 기체 반응·고체 수집', handling: '수용액 염산(HCl(aq))과 혼동하지 않는다.',
    gasVolumeRatio: { label: 'NH3 : HCl', ratio: '1 : 1', note: '반응물 기체의 동일 조건 부피비 (생성물은 고체)' },
    scientificSources: ['일반화학 교과서: 암모니아와 염화수소의 반응'],
    simplifications: [],
    modes: ['industrial'], path: 'gas',
  }),
  R20: R({
    id: 'R20', name: '암모니아 합성(부분 전환)', equation: 'N2(g) + 3H2(g) ⇌ 2NH3(g)',
    reactants: [{ accepts: ['N2_g'], coef: 1 }, { accepts: ['H2_g'], coef: 3 }],
    products: [{ materialId: 'NH3_g', coef: 2 }],
    batchMultiplier: 2,
    extentModel: { type: 'partial', extent: 1, note: '배치 N2 2칸 + H2 6칸 투입 → extent 1칸만큼 진행. 실제 평형 실측값이 아닌 게임 모델.' },
    outputs: [{ products: [{ materialId: 'NH3_g', coef: 2 }, { materialId: 'N2_g', coef: 1 }, { materialId: 'H2_g', coef: 3 }], tags: ['gasMixture', 'partial'], mixture: true }],
    energy: 3, time: 3, timeWithCatalyst: 2, catalystEquipment: 'U09', requiredEquipment: ['U06'], exothermic: true, heatRecoverable: false,
    conditions: '고압·가열, Fe 촉매 선택', handling: '정제 모듈(P04)로 암모니아를 분리하고 남은 원료를 회수한다. 촉매는 전환량을 바꾸지 않는다.',
    gasVolumeRatio: { label: 'N2 : H2 : NH3', ratio: '1 : 3 : 2', note: '동일 조건으로 환산한 이상기체 기준. 실제 운전 부피가 아니다.' },
    scientificSources: ['일반화학 교과서: 하버 공정과 평형', 'UCalgary Chem Textbook: 촉매와 평형'],
    simplifications: ['50% 전환은 단순화된 경기 모델이다.'],
    modes: ['industrial'], path: 'gas',
  }),
  R21: R({
    id: 'R21', name: '알코올 발효', equation: 'C6H12O6(aq) → 2C2H5OH(aq) + 2CO2(g)',
    reactants: [{ accepts: ['glucose_aq'], coef: 1 }],
    products: [{ materialId: 'ethanol_aq', coef: 2 }, { materialId: 'CO2_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CO2_g', coef: 2 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'ethanol_aq', coef: 2 }], tags: ['reaction'], solvent: 1 },
    ],
    energy: 0, time: 2, exothermic: true, heatRecoverable: false,
    conditions: '효모를 이용한 알코올 발효', handling: '생체량 등을 생략한 총괄식 모델. 에탄올은 정제(P04)가 필요하다.',
    scientificSources: ['일반화학·생물 교과서: 알코올 발효 총괄식'],
    simplifications: ['효모 생체량·부산물은 생략한 총괄식이다.'],
    modes: ['industrial'], path: 'bio',
  }),
  R22: R({
    id: 'R22', name: '에스터화(부분 전환)', equation: 'CH3COOH(l) + C2H5OH(l) ⇌ CH3COOC2H5(l) + H2O(l)',
    reactants: [{ accepts: ['aceticAcid_l'], coef: 1 }, { accepts: ['ethanol_l'], coef: 1 }],
    products: [{ materialId: 'ethylAcetate_l', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 2,
    extentModel: { type: 'partial', extent: 1, note: '산 2칸 + 알코올 2칸 투입 → 에스터 1칸 + 물 1칸 + 각 미반응물 1칸. 단순화된 경기 모델.' },
    outputs: [{ products: [{ materialId: 'ethylAcetate_l', coef: 1 }, { materialId: 'H2O_l', coef: 1 }, { materialId: 'aceticAcid_l', coef: 1 }, { materialId: 'ethanol_l', coef: 1 }], tags: ['liquidMixture', 'partial'], mixture: true }],
    energy: 2, time: 3, timeWithCatalyst: 2, catalystEquipment: 'U10', exothermic: false, heatRecoverable: false,
    conditions: '가열·산 촉매 선택', handling: '정제 모듈(P04)의 검증된 분리 모델로 에스터를 회수한다.',
    scientificSources: ['RSC Education: 알코올과 산으로 에스터 만들기'],
    simplifications: ['50% 전환은 단순화된 경기 모델이다. 식품 향료 등급을 보증하지 않는다.'],
    modes: ['industrial'], path: 'bio',
  }),
};

export const REACTION_IDS = Object.keys(REACTIONS);

export function reaction(id: string): ReactionDefinition {
  const r = REACTIONS[id];
  if (!r) throw new Error(`반응 없음: ${id}`);
  return r;
}
