import type { ReactionDefinition } from '../types';

/**
 * 반응 골격 22개. 화학식·계수·원소 보존은 밸런스 조정 대상이 아니다.
 * energy/time 은 추상 비용이며 economy config 가 덮어쓸 수 있다.
 * outputs 는 배치(batchMultiplier × 최소비) 기준으로 실제 생기는 로트 스트림이다.
 */
const R = (r: ReactionDefinition) => r;

export const REACTIONS: Record<string, ReactionDefinition> = {
  R01: R({
    id: 'R01', name: '수증기 만들기', equation: '2H2(g) + O2(g) → 2H2O(g)',
    reactants: [{ accepts: ['H2_g'], coef: 2 }, { accepts: ['O2_g'], coef: 1 }],
    products: [{ materialId: 'H2O_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'H2O_g', coef: 2 }], tags: ['reaction'] }],
    energy: 1, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '불꽃으로 점화, 닫힌 용기에서 모으기', handling: '수증기는 응축하기를 해야 액체 물이 된다.',
    gasVolumeRatio: { label: 'H2 : O2 : H2O(g)', ratio: '2 : 1 : 2', note: '수증기가 기체인 동일 온도·압력 조건에서의 부피비' },
    scientificSources: ['OpenStax Chemistry 2e §9.3 (기체 화학량론)'],
    simplifications: ['점화 조건과 안전 장치는 추상화했다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R02: R({
    id: 'R02', name: '물 쪼개기(전기분해)', equation: '2H2O(l) → 2H2(g) + O2(g)',
    reactants: [{ accepts: ['H2O_l'], coef: 2 }],
    products: [{ materialId: 'H2_g', coef: 2 }, { materialId: 'O2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'H2_g', coef: 2 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'O2_g', coef: 1 }], tags: ['gasCollected'] },
    ],
    energy: 4, time: 2, requiredEquipment: ['U05'], exothermic: false, heatRecoverable: false, heatKind: 'electric',
    conditions: '전해 모듈로 전기를 흘려 분해', handling: '수소와 산소는 서로 다른 전극에서 따로 모인다.',
    gasVolumeRatio: { label: 'H2 : O2', ratio: '2 : 1', note: '생성 기체의 동일 조건 부피비' },
    scientificSources: ['일반화학 교과서: 물의 전기분해'],
    simplifications: ['순수한 물은 전기가 거의 통하지 않아, 실제로는 황산나트륨 같은 물질을 조금 녹여 넣는다. 이 물질은 반응 뒤에도 그대로 남아서 게임에서는 따로 세지 않는다.'],
    modes: ['extended', 'industrial'], path: 'gas',
  }),
  R03: R({
    id: 'R03', name: '산소 만들기(과산화수소 분해)', equation: '2H2O2(aq) → 2H2O(l) + O2(g)',
    reactants: [{ accepts: ['H2O2_aq'], coef: 2 }],
    products: [{ materialId: 'H2O_l', coef: 2 }, { materialId: 'O2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'O2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'H2O_l', coef: 2 }], tags: ['solutionWater'], grade: 'recovered', solvent: 2 },
    ],
    energy: 0, time: 2, timeWithCatalyst: 1, catalystEquipment: 'U08', exothermic: true, heatRecoverable: false,
    conditions: '그냥 두면 천천히 분해, 이산화망가니즈 촉매가 있으면 빠름', handling: '산소는 따로 모으고, 물은 회수수로 남는다.',
    scientificSources: ['일반화학 교과서: 촉매에 의한 과산화수소 분해'],
    simplifications: ['과산화수소수에서 나온 물은 회수수라서 깨끗한 물 의뢰에는 쓸 수 없다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R04: R({
    id: 'R04', name: '메테인 태우기', equation: 'CH4(g) + 2O2(g) → CO2(g) + 2H2O(g)',
    reactants: [{ accepts: ['CH4_g'], coef: 1 }, { accepts: ['O2_g'], coef: 2 }],
    products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 2 }], tags: ['gasMixture'], mixture: true }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '산소가 충분한 완전 연소', handling: '섞인 기체를 응축하기로 식히면 물과 이산화탄소가 나뉜다.',
    gasVolumeRatio: { label: 'CH4 : O2 : CO2 : H2O(g)', ratio: '1 : 2 : 1 : 2', note: '모두 기체인 동일 조건 부피비' },
    scientificSources: ['OpenStax Chemistry 2e §9.3'],
    simplifications: ['불완전 연소는 다루지 않는다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'gas',
  }),
  R05: R({
    id: 'R05', name: '마그네슘 태우기', equation: '2Mg(s) + O2(g) → 2MgO(s)',
    reactants: [{ accepts: ['Mg_s'], coef: 2 }, { accepts: ['O2_g'], coef: 1 }],
    products: [{ materialId: 'MgO_s', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'MgO_s', coef: 2 }], tags: ['reaction'] }],
    energy: 1, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '점화, 산소 조건', handling: '산화마그네슘을 바로 회수한다.',
    scientificSources: ['일반화학 교과서: 금속의 연소'],
    simplifications: ['공기 중 질소와의 부반응은 생략했다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'metal',
  }),
  R06: R({
    id: 'R06', name: '베이킹소다 가열하기', equation: '2NaHCO3(s) → Na2CO3(s) + CO2(g) + H2O(g)',
    reactants: [{ accepts: ['NaHCO3_s'], coef: 2 }],
    products: [{ materialId: 'Na2CO3_s', coef: 1 }, { materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'Na2CO3_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_g', coef: 1 }], tags: ['gasMixture'], mixture: true },
    ],
    energy: 2, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '가열', handling: '고체와 기체는 따로 나온다. 섞인 기체(이산화탄소+수증기)는 응축하기로 나눈다.',
    gasVolumeRatio: { label: 'CO2 : H2O(g)', ratio: '1 : 1', note: '수증기가 기체인 같은 온도·압력에서 생긴 두 기체의 부피비' },
    scientificSources: ['RSC Education: 탄산염의 가열'],
    simplifications: ['완전 분해로 가정한다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R07: R({
    id: 'R07', name: '탄산칼슘 만들기(앙금 생성)', equation: 'Na2CO3(aq) + CaCl2(aq) → CaCO3(s) + 2NaCl(aq)',
    reactants: [{ accepts: ['Na2CO3_s'], coef: 1, dissolve: true }, { accepts: ['CaCl2_aq', 'CaCl2_s'], coef: 1, dissolve: true }],
    products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'NaCl_aq', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'NaCl_aq', coef: 2 }], tags: ['suspension'], mixture: true, solvent: 2 }],
    energy: 0, time: 1, exothermic: false, heatRecoverable: false, heatKind: 'small',
    conditions: '두 수용액을 섞으면 흰 앙금이 생김', handling: '거르기로 탄산칼슘을 건져 내고, 남은 소금물(염화나트륨 수용액)은 따로 보관한다.',
    scientificSources: ['CU Boulder Lecture Demo S130: CaCl2 + Na2CO3 침전'],
    simplifications: ['고체 재료는 공방의 물에 녹여서 넣는다. 그 물은 게임에서 따로 세지 않는다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R08: R({
    id: 'R08', name: '생석회에 물 붓기', equation: 'CaO(s) + H2O(l) → Ca(OH)2(s)',
    reactants: [{ accepts: ['CaO_s'], coef: 1 }, { accepts: ['H2O_l'], coef: 1 }],
    products: [{ materialId: 'CaOH2_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaOH2_s', coef: 1 }], tags: ['reaction'] }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '생석회에 물을 부어 섞기', handling: '수산화칼슘(소석회)이 생긴다.',
    scientificSources: ['일반화학 교과서: 산화칼슘의 수화'],
    simplifications: [],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R09: R({
    id: 'R09', name: '석회수에 이산화탄소 넣기', equation: 'Ca(OH)2(aq) + CO2(g) → CaCO3(s) + H2O(l)',
    reactants: [{ accepts: ['CaOH2_s'], coef: 1, dissolve: true }, { accepts: ['CO2_g'], coef: 1 }],
    products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CaCO3_s', coef: 1 }, { materialId: 'H2O_l', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '석회수(수산화칼슘을 물에 녹인 것)에 이산화탄소 넣기', handling: '뿌옇게 생긴 탄산칼슘 앙금을 거르기로 건져 낸다.',
    scientificSources: ['일반화학 교과서: 석회수의 백탁'],
    simplifications: ['이산화탄소를 너무 많이 넣으면 앙금이 다시 녹아 맑아지지만, 이 게임에서는 다루지 않는다.'],
    modes: ['classic', 'extended', 'industrial'], path: 'carbonate',
  }),
  R10: R({
    id: 'R10', name: '산과 염기 섞기(중화)', equation: 'HCl(aq) + NaOH(aq) → NaCl(aq) + H2O(l)',
    reactants: [{ accepts: ['HCl_aq'], coef: 1 }, { accepts: ['NaOH_aq'], coef: 1 }],
    products: [{ materialId: 'NaCl_aq', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'NaCl_aq', coef: 1 }], tags: ['reaction'], solvent: 3 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: true,
    conditions: '산과 염기 섞기', handling: '소금물이 생긴다. 소금을 얻으려면 결정 만들기가 필요하다. 생긴 물은 소금물에 합쳐진다.',
    scientificSources: ['일반화학 교과서: 산염기 중화'],
    simplifications: ['생긴 물 1개는 따로 나오지 않고 소금물에 합쳐진다.'],
    modes: ['extended', 'industrial'], path: 'water',
  }),
  R11: R({
    id: 'R11', name: '탄산칼슘에 염산 붓기', equation: 'CaCO3(s) + 2HCl(aq) → CaCl2(aq) + CO2(g) + H2O(l)',
    reactants: [{ accepts: ['CaCO3_s'], coef: 1 }, { accepts: ['HCl_aq'], coef: 2 }],
    products: [{ materialId: 'CaCl2_aq', coef: 1 }, { materialId: 'CO2_g', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CO2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'CaCl2_aq', coef: 1 }], tags: ['reaction'], solvent: 3 },
    ],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '탄산칼슘에 염산을 부으면 거품이 남', handling: '이산화탄소는 따로 모으고, 염화칼슘 수용액은 따로 남는다.',
    scientificSources: ['일반화학 교과서: 탄산염과 산의 반응'],
    simplifications: ['생긴 물은 따로 나오지 않고 염화칼슘 수용액에 합쳐진다.'],
    modes: ['extended', 'industrial'], path: 'carbonate',
  }),
  R12: R({
    id: 'R12', name: '마그네슘에 염산 붓기', equation: 'Mg(s) + 2HCl(aq) → MgCl2(aq) + H2(g)',
    reactants: [{ accepts: ['Mg_s'], coef: 1 }, { accepts: ['HCl_aq'], coef: 2 }],
    products: [{ materialId: 'MgCl2_aq', coef: 1 }, { materialId: 'H2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'H2_g', coef: 1 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'MgCl2_aq', coef: 1 }], tags: ['reaction'], solvent: 2 },
    ],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '마그네슘에 염산을 부으면 거품이 남', handling: '수소는 따로 모으고, 염화마그네슘 수용액은 따로 남는다.',
    scientificSources: ['일반화학 교과서: 금속과 산의 반응'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R13: R({
    id: 'R13', name: '아연으로 구리 꺼내기', equation: 'Zn(s) + CuSO4(aq) → ZnSO4(aq) + Cu(s)',
    reactants: [{ accepts: ['Zn_s'], coef: 1 }, { accepts: ['CuSO4_aq'], coef: 1 }],
    products: [{ materialId: 'ZnSO4_aq', coef: 1 }, { materialId: 'Cu_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'ZnSO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '아연이 구리 이온을 밀어냄', handling: '생긴 구리를 거르기로 건져 낸다.',
    scientificSources: ['일반화학 교과서: 금속의 반응성 서열'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R14: R({
    id: 'R14', name: '산화구리에서 구리 뽑기', equation: 'CuO(s) + H2(g) → Cu(s) + H2O(g)',
    reactants: [{ accepts: ['CuO_s'], coef: 1 }, { accepts: ['H2_g'], coef: 1 }],
    products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'Cu_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'H2O_g', coef: 1 }], tags: ['reaction'] },
    ],
    energy: 2, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '처음에 가열해야 시작 (수소가 산화구리의 산소를 가져감)', handling: '구리와 수증기가 따로 나온다. 수증기는 응축하기를 해야 물이 된다.',
    gasVolumeRatio: { label: 'H2 : H2O(g)', ratio: '1 : 1', note: '수증기가 기체인 같은 온도·압력에서의 부피비' },
    scientificSources: ['일반화학 교과서: 금속 산화물의 환원'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R15: R({
    id: 'R15', name: '석회석 굽기', equation: 'CaCO3(s) → CaO(s) + CO2(g)',
    reactants: [{ accepts: ['CaCO3_s'], coef: 1 }],
    products: [{ materialId: 'CaO_s', coef: 1 }, { materialId: 'CO2_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CaO_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'CO2_g', coef: 1 }], tags: ['gasCollected'] },
    ],
    energy: 3, time: 2, exothermic: false, heatRecoverable: false,
    conditions: '아주 세게 가열해 분해', handling: '탄산칼슘을 그대로 배달할지, 구워서 생석회로 쓸지 골라야 한다.',
    scientificSources: ['RSC Education: 탄산염의 가열'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'carbonate',
  }),
  R16: R({
    id: 'R16', name: '수산화구리 만들기(앙금 생성)', equation: 'CuSO4(aq) + 2NaOH(aq) → Cu(OH)2(s) + Na2SO4(aq)',
    reactants: [{ accepts: ['CuSO4_aq'], coef: 1 }, { accepts: ['NaOH_aq'], coef: 2 }],
    products: [{ materialId: 'CuOH2_s', coef: 1 }, { materialId: 'Na2SO4_aq', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'CuOH2_s', coef: 1 }, { materialId: 'Na2SO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 3 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '두 수용액을 섞으면 파란 앙금이 생김', handling: '파란 앙금을 거르기로 건져 낸다.',
    scientificSources: ['일반화학 교과서: 침전 반응'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R17: R({
    id: 'R17', name: '수산화구리 가열하기', equation: 'Cu(OH)2(s) → CuO(s) + H2O(g)',
    reactants: [{ accepts: ['CuOH2_s'], coef: 1 }],
    products: [{ materialId: 'CuO_s', coef: 1 }, { materialId: 'H2O_g', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CuO_s', coef: 1 }], tags: ['reaction'] },
      { products: [{ materialId: 'H2O_g', coef: 1 }], tags: ['reaction'] },
    ],
    energy: 2, time: 1, exothermic: false, heatRecoverable: false,
    conditions: '가열해 분해', handling: '수증기는 응축하기를 해야 액체 물이 된다.',
    scientificSources: ['일반화학 교과서: 수산화물의 열분해'],
    simplifications: [],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R18: R({
    id: 'R18', name: '철로 구리 꺼내기', equation: 'Fe(s) + CuSO4(aq) → FeSO4(aq) + Cu(s)',
    reactants: [{ accepts: ['Fe_s'], coef: 1 }, { accepts: ['CuSO4_aq'], coef: 1 }],
    products: [{ materialId: 'FeSO4_aq', coef: 1 }, { materialId: 'Cu_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'Cu_s', coef: 1 }, { materialId: 'FeSO4_aq', coef: 1 }], tags: ['suspension'], mixture: true, solvent: 1 }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '철이 구리 이온을 밀어냄', handling: '생긴 구리를 거르기로 건져 낸다. 아연으로 꺼낼 때와 비용을 비교해 보자.',
    scientificSources: ['일반화학 교과서: 금속의 반응성 서열'],
    simplifications: ['재료로 쓰는 철과 철 촉매 모듈(장비)은 서로 다른 것이다. 재료 철은 반응에서 없어지고, 촉매 모듈은 닳지 않는다.'],
    modes: ['extended', 'industrial'], path: 'metal',
  }),
  R19: R({
    id: 'R19', name: '염화암모늄 만들기', equation: 'NH3(g) + HCl(g) → NH4Cl(s)',
    reactants: [{ accepts: ['NH3_g'], coef: 1 }, { accepts: ['HCl_g'], coef: 1 }],
    products: [{ materialId: 'NH4Cl_s', coef: 1 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [{ products: [{ materialId: 'NH4Cl_s', coef: 1 }], tags: ['reaction'] }],
    energy: 0, time: 1, exothermic: true, heatRecoverable: false,
    conditions: '두 기체가 만나면 흰 고체가 생김', handling: '기체 염화수소를 쓴다. 물에 녹인 염산과는 다른 재료다.',
    gasVolumeRatio: { label: 'NH3 : HCl', ratio: '1 : 1', note: '반응물 기체의 동일 조건 부피비 (생성물은 고체)' },
    scientificSources: ['일반화학 교과서: 암모니아와 염화수소의 반응'],
    simplifications: [],
    modes: ['industrial'], path: 'gas',
  }),
  R20: R({
    id: 'R20', name: '암모니아 만들기', equation: 'N2(g) + 3H2(g) ⇌ 2NH3(g)',
    reactants: [{ accepts: ['N2_g'], coef: 1 }, { accepts: ['H2_g'], coef: 3 }],
    products: [{ materialId: 'NH3_g', coef: 2 }],
    batchMultiplier: 2,
    extentModel: { type: 'partial', extent: 1, note: '질소 2개 + 수소 6개를 넣으면 절반만 반응해 암모니아 2개가 생기고, 질소 1개와 수소 3개는 그대로 섞여 나와요. ⇌ 표시는 반응물이 다 바뀌지 않고 생성물과 함께 남는다는 뜻이에요. 실제 공장의 수치가 아니라 게임용으로 정한 값이에요.' },
    outputs: [{ products: [{ materialId: 'NH3_g', coef: 2 }, { materialId: 'N2_g', coef: 1 }, { materialId: 'H2_g', coef: 3 }], tags: ['gasMixture', 'partial'], mixture: true }],
    energy: 3, time: 3, timeWithCatalyst: 2, catalystEquipment: 'U09', requiredEquipment: ['U06'], exothermic: true, heatRecoverable: false,
    conditions: '높은 압력·가열, 철 촉매가 있으면 빠름', handling: '정제하기로 암모니아만 골라내고 남은 질소·수소를 돌려받는다. 촉매는 빨리 만들 뿐 만들어지는 양은 바꾸지 않는다.',
    gasVolumeRatio: { label: 'N2 : H2 : NH3', ratio: '1 : 3 : 2', note: '같은 온도·압력으로 맞춰 비교한 부피비. 실제 공장에서 쓰는 부피가 아니다.' },
    scientificSources: ['일반화학 교과서: 하버 공정과 평형', 'UCalgary Chem Textbook: 촉매와 평형'],
    simplifications: ['절반만 반응하는 것은 게임용으로 단순하게 정한 값이다. 실제 공장에서 한 번에 바뀌는 양은 이보다 적다.'],
    modes: ['industrial'], path: 'gas',
  }),
  R21: R({
    id: 'R21', name: '발효로 에탄올 만들기', equation: 'C6H12O6(aq) → 2C2H5OH(aq) + 2CO2(g)',
    reactants: [{ accepts: ['glucose_aq'], coef: 1 }],
    products: [{ materialId: 'ethanol_aq', coef: 2 }, { materialId: 'CO2_g', coef: 2 }],
    batchMultiplier: 1, extentModel: { type: 'full' },
    outputs: [
      { products: [{ materialId: 'CO2_g', coef: 2 }], tags: ['gasCollected'] },
      { products: [{ materialId: 'ethanol_aq', coef: 2 }], tags: ['reaction'], solvent: 1 },
    ],
    energy: 0, time: 2, exothermic: true, heatRecoverable: false,
    conditions: '효모를 이용한 알코올 발효', handling: '에탄올은 물에 섞여 나오므로 정제하기가 필요하다.',
    scientificSources: ['일반화학·생물 교과서: 알코올 발효 총괄식'],
    simplifications: ['효모 자체나 다른 부산물은 빼고, 전체 변화만 적은 식이다.'],
    modes: ['industrial'], path: 'bio',
  }),
  R22: R({
    id: 'R22', name: '에스터 만들기', equation: 'CH3COOH(l) + C2H5OH(l) ⇌ CH3COOC2H5(l) + H2O(l)',
    reactants: [{ accepts: ['aceticAcid_l'], coef: 1 }, { accepts: ['ethanol_l'], coef: 1 }],
    products: [{ materialId: 'ethylAcetate_l', coef: 1 }, { materialId: 'H2O_l', coef: 1 }],
    batchMultiplier: 2,
    extentModel: { type: 'partial', extent: 1, note: '아세트산 2개 + 에탄올 2개를 넣으면 절반만 반응해 아세트산에틸 1개와 물 1개가 생기고, 아세트산 1개와 에탄올 1개는 그대로 섞여 나와요. ⇌ 표시는 반응물이 다 바뀌지 않고 생성물과 함께 남는다는 뜻이에요. 게임용으로 단순하게 정한 값이에요.' },
    outputs: [{ products: [{ materialId: 'ethylAcetate_l', coef: 1 }, { materialId: 'H2O_l', coef: 1 }, { materialId: 'aceticAcid_l', coef: 1 }, { materialId: 'ethanol_l', coef: 1 }], tags: ['liquidMixture', 'partial'], mixture: true }],
    energy: 2, time: 3, timeWithCatalyst: 2, catalystEquipment: 'U10', exothermic: false, heatRecoverable: false, heatKind: 'small',
    conditions: '빨리 반응하도록 가열, 산 촉매가 있으면 더 빠름', handling: '정제하기로 아세트산에틸만 골라내고 남은 재료를 돌려받는다.',
    scientificSources: ['RSC Education: 알코올과 산으로 에스터 만들기'],
    simplifications: ['절반만 반응하는 것은 게임용으로 단순하게 정한 값이다. 식품 향료로 쓸 만큼 순수하다는 뜻은 아니다.'],
    modes: ['industrial'], path: 'bio',
  }),
};

export const REACTION_IDS = Object.keys(REACTIONS);

/** 학생 화면의 열 출입 표시. 실온에서 저절로 일어나는 반응을 '열을 넣어야 한다'고 쓰지 않는다. */
export function heatLabel(r: ReactionDefinition): string {
  if (r.heatKind === 'electric') return '전기가 필요한 반응';
  if (r.heatKind === 'small') return '열 출입이 작은 반응';
  return r.exothermic ? '열이 나는 반응' : '열을 계속 넣어야 하는 반응';
}

export function reaction(id: string): ReactionDefinition {
  const r = REACTIONS[id];
  if (!r) throw new Error(`반응 없음: ${id}`);
  return r;
}
